apiVersion: apps/v1
kind: Deployment
metadata:
  name: eddybot
  labels:
    app: eddybot
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: eddybot
  template:
    metadata:
      labels:
        app: eddybot
    spec:
      containers:
      - name: eddybot
        image: eddybot:latest
        resources:
          limits:
            cpu: "2000m"
